runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: /css
  static_dir: /static/css
  secure: always

- url: /fonts
  static_dir: /static/fonts
  secure: always

- url: /scripts
  static_dir: /static/scripts
  secure: always

- url: /images
  static_dir: static/images
  secure: always

- url: /.*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest